"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "pt" | "en" | "es";
const Context = createContext<{language:Language;setLanguage:(value:Language)=>void}>({language:"pt",setLanguage:()=>undefined});

const dictionaries:Record<"en"|"es",Record<string,string>>={
en:{
"Ir para o conteúdo":"Skip to content","China · Brasil":"China · Brazil","Capital e estrutura para importar melhor.":"Capital and structure to import better.","Crédito na origem, fornecedores validados e gestão da operação internacional em uma única estrutura.":"Credit at origin, validated suppliers and international operation management in one structure.","Solicitar análise":"Request an assessment","Conhecer as soluções":"Explore solutions","Operação internacional":"International operation","FOB financiável":"Financeable FOB","Até 100%":"Up to 100%","Prazo estimado":"Estimated term","90–180 dias":"90–180 days","Condições sujeitas à análise cadastral, documental e financeira.":"Terms subject to corporate, documentary and financial assessment.","Soluções":"Solutions","Uma estrutura para cada etapa da operação.":"A structure for every stage of the operation.","Pagamento ao fornecedor na origem e prazo para sua empresa no Brasil.":"Payment to the supplier at origin and extended terms for your company in Brazil.","Procurement Internacional":"International Procurement","Busca, validação e negociação com fornecedores na China.":"Supplier search, validation and negotiation in China.","Produtos da China":"Products from China","Operações de compra em lote com suporte da origem à entrega.":"Bulk purchasing with support from origin to delivery.","Saiba mais":"Learn more","Estrutura empresarial":"Business structure","A TradeK conecta empresas brasileiras à Ásia com capital, execução e controle.":"TradeK connects Brazilian companies to Asia with capital, execution and control.","Conheça a TradeK":"About TradeK","Próxima operação":"Next operation","Vamos avaliar sua importação.":"Let’s assess your import operation.","Falar com um especialista":"Talk to a specialist","Produtos":"Products","A TradeK":"About TradeK","Abrir menu":"Open menu","Estrutura financeira e operacional para empresas que importam da Ásia.":"Financial and operational structure for companies importing from Asia.","Contato":"Contact","A TradeK não é uma instituição financeira.":"TradeK is not a financial institution.",
"← Voltar ao início":"← Back to home","Operação conectada":"Connected operation","Próximo passo":"Next step","Estruture sua próxima operação com mais controle.":"Structure your next operation with greater control.","Seu fornecedor recebe à vista. Seu caixa continua respirando.":"Your supplier gets paid upfront. Your cash flow keeps moving.","Pague seu fornecedor na Ásia à vista e acesse prazos de até 180 dias para liquidação. A TradeK estrutura crédito, negociação e gestão da operação.":"Pay your supplier in Asia upfront and access terms of up to 180 days. TradeK structures credit, negotiation and operation management.","Avaliar minha importação":"Assess my import","Como funciona":"How it works","Análise":"Assessment","Crédito na origem":"Credit at origin","Pagamento ao fornecedor":"Supplier payment","Prazo no Brasil":"Terms in Brazil","Crédito estruturado na Ásia":"Credit structured in Asia","Sem exigência de garantias locais":"No local collateral requirement","Pagamento direto ao fornecedor":"Direct payment to the supplier","Preservação do capital de giro":"Working capital preservation","Operação integrada de crédito e pagamento":"Integrated credit and payment operation",
"Fornecedores certos, negociados na origem.":"The right suppliers, negotiated at origin.","Iniciar um briefing":"Start a briefing","Etapas do processo":"Process stages","Briefing da operação":"Operation briefing","Sourcing estratégico":"Strategic sourcing","Validação de fornecedores":"Supplier validation","Negociação na origem":"Negotiation at origin","Inspeção e qualidade":"Inspection and quality","Dados para o briefing":"Briefing information","Produtos na origem, prontos para escalar no Brasil.":"Products at origin, ready to scale in Brazil.","Iniciar compra para revenda":"Start a resale purchase","Da seleção à revenda":"From selection to resale","Seleção do produto":"Product selection","Estruturação do lote":"Lot structuring","Importação com prazo":"Import with extended terms","Revenda no Brasil":"Resale in Brazil","Operação assistida":"Assisted operation",
"Fale conosco":"Contact us","Vamos estruturar sua próxima operação.":"Let’s structure your next operation.","Compartilhe o contexto da sua empresa. Nossa equipe analisa a demanda e retorna com o próximo passo.":"Share your company’s context. Our team will assess the request and return with the next step.","Operação":"Operation","Solicitação de análise":"Assessment request","Nome":"Name","Seu nome":"Your name","Empresa":"Company","Nome da empresa":"Company name","Unidade de interesse":"Area of interest","Mensagem":"Message","Produto, volume, prazo e objetivo da operação...":"Product, volume, timing and operation goal...","Enviar solicitação":"Send request","Central de ajuda":"Help center","Perguntas frequentes":"Frequently asked questions","Quem somos":"Who we are","A ponte entre crédito, produto e operação na China.":"The bridge between credit, products and operations in China.","O que nos move":"What drives us","Nossos valores":"Our values","O que sustenta a TradeK":"What TradeK stands for"
},
es:{
"Ir para o conteúdo":"Ir al contenido","Capital e estrutura para importar melhor.":"Capital y estructura para importar mejor.","Crédito na origem, fornecedores validados e gestão da operação internacional em uma única estrutura.":"Crédito en origen, proveedores validados y gestión internacional en una sola estructura.","Solicitar análise":"Solicitar análisis","Conhecer as soluções":"Conocer las soluciones","Operação internacional":"Operación internacional","FOB financiável":"FOB financiable","Até 100%":"Hasta 100%","Prazo estimado":"Plazo estimado","90–180 dias":"90–180 días","Condições sujeitas à análise cadastral, documental e financeira.":"Condiciones sujetas a análisis registral, documental y financiero.","Soluções":"Soluciones","Uma estrutura para cada etapa da operação.":"Una estructura para cada etapa de la operación.","Pagamento ao fornecedor na origem e prazo para sua empresa no Brasil.":"Pago al proveedor en origen y plazo para su empresa en Brasil.","Busca, validação e negociação com fornecedores na China.":"Búsqueda, validación y negociación con proveedores en China.","Produtos da China":"Productos de China","Operações de compra em lote com suporte da origem à entrega.":"Compra por lote con soporte desde el origen hasta la entrega.","Saiba mais":"Más información","Estrutura empresarial":"Estructura empresarial","A TradeK conecta empresas brasileiras à Ásia com capital, execução e controle.":"TradeK conecta empresas brasileñas con Asia mediante capital, ejecución y control.","Conheça a TradeK":"Conozca TradeK","Próxima operação":"Próxima operación","Vamos avaliar sua importação.":"Evaluemos su importación.","Falar com um especialista":"Hablar con un especialista","Produtos":"Productos","A TradeK":"Sobre TradeK","Abrir menu":"Abrir menú","Estrutura financeira e operacional para empresas que importam da Ásia.":"Estructura financiera y operativa para empresas que importan de Asia.","Contato":"Contacto","A TradeK não é uma instituição financeira.":"TradeK no es una institución financiera.",
"← Voltar ao início":"← Volver al inicio","Operação conectada":"Operación conectada","Próximo passo":"Próximo paso","Estruture sua próxima operação com mais controle.":"Estructure su próxima operación con mayor control.","Seu fornecedor recebe à vista. Seu caixa continua respirando.":"Su proveedor cobra al contado. Su flujo de caja sigue activo.","Avaliar minha importação":"Evaluar mi importación","Como funciona":"Cómo funciona","Análise":"Análisis","Crédito na origem":"Crédito en origen","Pagamento ao fornecedor":"Pago al proveedor","Prazo no Brasil":"Plazo en Brasil","Crédito estruturado na Ásia":"Crédito estructurado en Asia","Sem exigência de garantias locais":"Sin garantías locales","Pagamento direto ao fornecedor":"Pago directo al proveedor","Preservação do capital de giro":"Preservación del capital de trabajo","Operação integrada de crédito e pagamento":"Operación integrada de crédito y pago","Fornecedores certos, negociados na origem.":"Proveedores adecuados, negociados en origen.","Iniciar um briefing":"Iniciar un briefing","Etapas do processo":"Etapas del proceso","Briefing da operação":"Briefing de la operación","Sourcing estratégico":"Sourcing estratégico","Validação de fornecedores":"Validación de proveedores","Negociação na origem":"Negociación en origen","Inspeção e qualidade":"Inspección y calidad","Dados para o briefing":"Datos para el briefing","Produtos na origem, prontos para escalar no Brasil.":"Productos en origen, listos para escalar en Brasil.","Iniciar compra para revenda":"Iniciar compra para reventa","Da seleção à revenda":"De la selección a la reventa","Seleção do produto":"Selección del producto","Estruturação do lote":"Estructuración del lote","Importação com prazo":"Importación con plazo","Revenda no Brasil":"Reventa en Brasil","Operação assistida":"Operación asistida",
"Fale conosco":"Contáctenos","Vamos estruturar sua próxima operação.":"Estructuremos su próxima operación.","Compartilhe o contexto da sua empresa. Nossa equipe analisa a demanda e retorna com o próximo passo.":"Comparta el contexto de su empresa. Nuestro equipo analiza la solicitud y responde con el siguiente paso.","Operação":"Operación","Solicitação de análise":"Solicitud de análisis","Nome":"Nombre","Seu nome":"Su nombre","Nome da empresa":"Nombre de la empresa","Unidade de interesse":"Área de interés","Mensagem":"Mensaje","Produto, volume, prazo e objetivo da operação...":"Producto, volumen, plazo y objetivo de la operación...","Enviar solicitação":"Enviar solicitud","Central de ajuda":"Centro de ayuda","Perguntas frequentes":"Preguntas frecuentes","Quem somos":"Quiénes somos","A ponte entre crédito, produto e operação na China.":"El puente entre crédito, producto y operación en China.","O que nos move":"Lo que nos mueve","Nossos valores":"Nuestros valores","O que sustenta a TradeK":"Lo que sostiene a TradeK"
}};

const originals=new WeakMap<Text,string>();
function applyLanguage(language:Language){
 const dictionary=language==="pt"?{}:dictionaries[language]; document.documentElement.lang=language==="pt"?"pt-BR":language;
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); let node:Text|null;
 while((node=walker.nextNode() as Text|null)){if(node.parentElement?.closest("script,style"))continue;if(!originals.has(node))originals.set(node,node.data);const source=originals.get(node)!;const clean=source.trim();const next=dictionary[clean]?source.replace(clean,dictionary[clean]):source;if(node.data!==next)node.data=next;}
 document.querySelectorAll("[placeholder],[aria-label]").forEach(el=>{for(const attr of ["placeholder","aria-label"]){const source=el.getAttribute(`data-original-${attr}`)??el.getAttribute(attr);if(!source)continue;if(!el.hasAttribute(`data-original-${attr}`))el.setAttribute(`data-original-${attr}`,source);const next=dictionary[source]??source;if(el.getAttribute(attr)!==next)el.setAttribute(attr,next);}});
}
export function LanguageProvider({children}:{children:React.ReactNode}){const[language,setState]=useState<Language>("pt");useEffect(()=>{const saved=localStorage.getItem("tradek_language");if(saved==="en"||saved==="es")setState(saved)},[]);useEffect(()=>{applyLanguage(language);const observer=new MutationObserver(()=>applyLanguage(language));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[language]);const value=useMemo(()=>({language,setLanguage:(next:Language)=>{localStorage.setItem("tradek_language",next);setState(next)}}),[language]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useLanguage(){return useContext(Context)}
export function LanguageSwitcher(){const{language,setLanguage}=useLanguage();return <div className="language-switcher" aria-label="Language / Idioma">{(["pt","en","es"] as Language[]).map(item=><button type="button" key={item} className={language===item?"active":""} onClick={()=>setLanguage(item)} aria-pressed={language===item}>{item.toUpperCase()}</button>)}</div>}
